language: node_js
node_js:
  - '10'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - 'NODE_ENV=ci PORT=3000'
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - 'npm install'
  - 'npm run build'
jobs:
  include:
    -
      stage: start
      script: 'nohup npm run start &'
    -
      stage: test
      script: 'npm run test'
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    -
      stage: deploy
      provider:
        heroku
        app:
          master: advanced-node
          production: advanced-node
        api_key: ${HEROKU_API_KEY}"

# after_success:
# Generating code coverage for test files using Puppeteer is currently not possible
#  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
